language: java
env:
  global:
    - JAVA_OPTS="-XX:MaxPermSize=512m -Xmx4g"

jdk:
  - oraclejdk8
  - oraclejdk7
cache:
  directories:
    - $HOME/.gradle

install:
  - ./gradlew clean > /dev/null

script:
  - ./gradlew --info --full-stacktrace | sed s/^.*DEBUG.*$//
